apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: slack-gamebot
    run: slack-gamebot
  name: slack-gamebot
  namespace: ryan01
spec:
  replicas: 1
  selector:
    matchLabels:
      run: slack-gamebot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: slack-gamebot
        run: slack-gamebot
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: "mongodb://ryan01-mongodb-replicaset:27017/slack-gamebot"
        - name: LANG
          value: "en_US.UTF-8"
        - name: RACK_ENV
          value: "production"
        image: rliuasapp/slack-gamebot:v1.0
        imagePullPolicy: IfNotPresent
        name: slack-gamebot
        ports:
        - containerPort: 6060
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 6060
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 500M
          requests:
            cpu: 200m
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: slack-gamebot
    tier: http
    exposure: vpn
  name: slack-gamebot-ext
  namespace: ryan01
  annotations:
    dns.alpha.kubernetes.io/external: slack-gamebot.test.asapp.com
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:146051540007:certificate/e5309135-cb85-4511-930c-efc3a44dba03
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  ports:
  - protocol: TCP
    port: 433
    targetPort: 6060
  selector:
    app: slack-gamebot
    tier: http
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 144.121.114.178/32
    - 144.121.114.179/32